name: "Build, Test and Deploy"

on: [workflow_dispatch]

env:
  AZURE_WEBAPP_NAME: accounts-balance-viewer-api-core
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '6.0.400'
  PROJECT_NAME: 'AccountsBalanceViewer.API'

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
          
      - name: Replace Configs
        run: |
          dotnet user-secrets init --project AccountsBalanceViewer.API
          dotnet user-secrets set "ConnectionStrings:AccountsDB" ${{ secrets.CONNECTION_STRINGS_ACCOUNTS_DB }} --project AccountsBalanceViewer.API
          dotnet user-secrets set "Jwt:Key" ${{ secrets.JWT_KEY }} --project AccountsBalanceViewer.API
          dotnet user-secrets set "Jwt:Issuer" ${{ secrets.JWT_ISSUER }} --project AccountsBalanceViewer.API
          dotnet user-secrets set "Jwt:Audience" ${{ secrets.JWT_AUDIENCE }} --project AccountsBalanceViewer.API
          dotnet user-secrets set "Jwt:ExpireIn" ${{ secrets.JWT_EXPIRE_IN }} --project AccountsBalanceViewer.API
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore -c Release
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: Publish app for deploy
        run: dotnet publish ${{ env.PROJECT_NAME }} --no-build -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
